// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmurfsGame.Data;

#nullable disable

namespace SmurfsDAL.Migrations
{
    [DbContext(typeof(SmurfsDbContext))]
    [Migration("20260225085946_secondMigration")]
    partial class secondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("ForestId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForestId");

                    b.ToTable("Creatures");

                    b.HasDiscriminator<string>("CreatureType").HasValue("Creature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Forest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxX")
                        .HasColumnType("int");

                    b.Property<int>("MaxY")
                        .HasColumnType("int");

                    b.Property<int>("MinX")
                        .HasColumnType("int");

                    b.Property<int>("MinY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forests");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ForestId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForestId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.BzzFly", b =>
                {
                    b.HasBaseType("Smurfs.SmurfsBL.entities.Creature");

                    b.HasDiscriminator().HasValue("BzzFly");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Schtroumpf", b =>
                {
                    b.HasBaseType("Smurfs.SmurfsBL.entities.Creature");

                    b.Property<bool>("IsGrandSchtroumpf")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Schtroumpf");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Spider", b =>
                {
                    b.HasBaseType("Smurfs.SmurfsBL.entities.Creature");

                    b.HasDiscriminator().HasValue("Spider");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Berry", b =>
                {
                    b.HasBaseType("Smurfs.SmurfsBL.entities.Item");

                    b.HasDiscriminator().HasValue("Berry");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.BluePotion", b =>
                {
                    b.HasBaseType("Smurfs.SmurfsBL.entities.Item");

                    b.HasDiscriminator().HasValue("BluePotion");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.RedPotion", b =>
                {
                    b.HasBaseType("Smurfs.SmurfsBL.entities.Item");

                    b.HasDiscriminator().HasValue("RedPotion");
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Creature", b =>
                {
                    b.HasOne("Smurfs.SmurfsBL.entities.Forest", null)
                        .WithMany("Creatures")
                        .HasForeignKey("ForestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Item", b =>
                {
                    b.HasOne("Smurfs.SmurfsBL.entities.Forest", null)
                        .WithMany("Items")
                        .HasForeignKey("ForestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Smurfs.SmurfsBL.entities.Forest", b =>
                {
                    b.Navigation("Creatures");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
